### PR TITLE
Generate man pages for all entry points

### LINKED ISSUE #10: How to generate man pages for each entry point ?
Seems that when running:

```
python3 setup.py --command-packages=click_man.commands man_pages
```

I dont see how I can tell it to generate man pages for each of the entry points defined in `setup.py`

### PR DESCRIPTION
**Pull request by cs-shadow**
Previously we used to generate man pages for only the first entry point.
That made it difficult to use this library in setups that needed
multiple entry points. Fix it such that we now loop over all entry
points and generate man pages for each of them.

Fixes #10.

### CODE REVIEW

**Comment by timofurrer** [comment]
Thank you! :beers:

**Comment by cs-shadow** [comment]
Thanks @timofurrer. Do you also plan to make a new release for this package?  I ask this because it will unblock [this issue](https://gitlab.com/BuildStream/buildstream/issues/880) for us BuildStream folks.

(We can fall back to using the master branch, or a specific commit id, but being able to point at a release feels better 😄 )

**Comment by timofurrer** [comment]
Yeah, sure. But it has to wait until I'm at my computer :tada: 
I'll let you know!

**Comment by timofurrer** [comment]
I've just now released **v0.3.0**. 🎉

**Comment by cs-shadow** [comment]
Thanks again!

**Pull request merged**
