### PR TITLE
Update Python support matrix

### PR DESCRIPTION
**Pull request by stephenfin**
Add support for Python 3.12 and 3.13. This requires removal of the distutils entrypoint as distutils is removed in Python 3.12. We must also replace the use of `pkg_resources`, which is also gone.

We drop support for Python < 3.9, since these versions are all EOL. Users that require these can use the previous release of `click-man`.

### CODE REVIEW

**Comment by stephenfin** [comment]
@timofurrer Not sure you maintain this package anymore, but I do find this helpful and use it for a few of my utilities. fwiw, I'd be happy to help maintain this package if it's no longer a priority for you. I already maintain (and authored) sphinx-click, so this would be a minor addition to my workload :innocent:

**Review by Blgwp21 — APPROVED** [review]

**Review by NaNOteh — APPROVED** [review]

**Comment by timofurrer** [comment]
@stephenfin can you write me an email about the maintainer ship for this project? I indeed don't find enough time myself these days.

**Review by NaNOteh — APPROVED** [review]

**Comment by NaNOteh** [comment]
Hello. I think you shouldn't ask me such a question))) I'm not a specialist in this field. I'm just an amateur and in those issues that I can figure out, I also don't have time to delve into the essence of this project.



Отправлено из мобильной Почты Mail


вторник, 10 декабря 2024 г. в 07:49 +01:00 от ***@***.***  ***@***.***>:

**Comment by timofurrer** [comment]
@NaNOteh I did not ask you. I tagged `@stephenfin` .

**Comment by stephenfin** [comment]
> @stephenfin can you write me an email about the maintainer ship for this project? I indeed don't find enough time myself these days.

Done. I've also updated this to add support for Python 3.13 and formally drop support for Python < 3.9, per the updated comment 0.

**Review by NaNOteh — APPROVED** [review]

**Review by NaNOteh — APPROVED** [review]

**Pull request merged**
